# Changes here will be overwritten by Copier
_commit: v5.3.2-14-g8f2fd79
_src_path: gh:eccenca/cmem-plugin-template
author_mail: cmempy-developer@eccenca.com
author_name: eccenca GmbH
github_page: ''
project_description: Load and parse YAML documents.
project_slug: yaml2json
pypi: false

