# Changes here will be overwritten by Copier
_commit: v6.4.0-21-g01b4330
_src_path: gh:eccenca/cmem-plugin-template
author_mail: cmempy-developer@eccenca.com
author_name: eccenca GmbH
github_page: https://github.com/eccenca/cmem-plugin-yaml
project_description: Load and parse YAML documents.
project_slug: yaml
project_type: plugin
pypi: true

